### ISSUE TITLE
Add PRIs and MRIs

### ISSUE THREAD

**Issue by chadokruse** [grantmakers/profiles#55]
Add program related investments and mission related investments

Form 990PF
Part IX-B

TODOs
- [ ] Define paths to fields [0]
- [x] Research number of existing grantmakers with PRIs [1]
- [ ] Decide how to present [2]

[0] Paths
**Newer:**
`Return.ReturnData.IRS990PF.SumOfProgramRelatedInvstGrp`
Nested objects:
`Description1Txt`
`Expenses1Amt`
Plus others TBD (e.g. totals and references to additional attachments and schedules)

**Older**
TBD

[1] 2018 Filings index
15,022 filings have at least 1 PRI description (many likely with 'N/A' listed)
2,753 filings have at least 1 PRI expense listed
471 filings have expense not equal to '0'

Quick pull of 2018 PRIs [(Google Sheet here)](https://docs.google.com/spreadsheets/d/1icYA3K4bsKoql5MiUIpKv9tf9L0lG8SkAHrSk5wj6as/edit?usp=sharing)

Note: the quick pull link does not contain all PRIs contained in the 2018 IRS Form 990PF dataset. It's limited to just those PRIs listed in the main filing (e.g. does not contain PRIs included in an attachment to the filing) and is further limited to just those showing at least one expense amount not equal to 0.

The MongoDB query used in the quick pull
```
 db.getCollection('pf_2018').aggregate(
  [
    {
      '$match': {
        'Return.ReturnData.IRS990PF.SumOfProgramRelatedInvstGrp.Expenses1Amt': { $exists: true, $nin: [ '0' ] },
      },
    },    
    {
      '$group': {
        '_id': '$_id' ,
        'ein': {'$first': '$Index.EIN'},
        'foundation_name': {'$first': '$Index.OrganizationName'},
        'program_related_investments': {'$first': '$Return.ReturnData.IRS990PF.SumOfProgramRelatedInvstGrp'}
      },
    },
  ]
);
```

[2] Options to present:
1. Separate search tool
2. Include in grants search results
