### ISSUE TITLE
Simplify intra-app search

### ISSUE THREAD

**Issue by chadokruse** [grantmakers/profiles#59]
Visitors are not finding Profiles Search at bottom of profiles (need to quantify)

Visitors are not finding Grants Search (e.g. keyword search)

Visitors searching for keywords in name-focused search boxes
- [ ] Main profiles search
- [ ] Profiles bottom CTA

TODOs
- [x] Clarify difference b/w Research and Prospecting (Profiles Search vs Grants Search)
- [x] ~~Consider merging searches into a single search~~
